# Initial buffer time budget.
BUFFER_TIME_BUDGET: 0
# The number of ticks to delay when agent decides not to assign VM.
DELAY_DURATION: 1

VM_TABLE: "/mnt/d/kuanwei/data/test_10k/build/vmtable.bin"

CPU_READINGS: "/mnt/d/kuanwei/data/test_10k/build/vm_cpu_readings-file-1-of-195.bin"

PM:
  P1:
    AMOUNT: 100
    CPU: 32
    MEMORY: 128
    # GPU: 4
    POWER_CURVE:
      # The calibration parameter used for the CPU utilization vs energy consumption model.
      CALIBRATION_PARAMETER: 1.4
      # The idle power usage of a machine.
      BUSY_POWER: 10
      # The busy power usage of a machine.
      IDLE_POWER: 1
