PM_NODES:
  P1:
    Amount: 880
    CPU: 16
    Memory: 112
    GPU: 4
    Power_Curve:
      # The calibration parameter used for the CPU utilization vs energy consumption model.
      calibration_parameter: 1.4
      # The idle power usage of a machine.
      busy_power: 10
      # The busy power usage of a machine.
      idle_power: 1
