# The number of ticks to delay when agent decides not to assign VM.
delay_duration: 1
# The calibration parameter used for the CPU utilization vs energy consumption model.
calibration_parameter: 1.4
# The idle power usage of a machine.
busy_power: 10
# The busy power usage of a machine.
idle_power: 1

vm_table: "~/.maro/data/data_center/.build/azure.2019.original/vmtable.bin"
